// src/lib/components/language-selector.svelte
<script lang="ts">
	import { m } from '$lib/paraglide/messages';
	import { getLocale, locales, setLocale, type Locale } from '$lib/paraglide/runtime';
	import { IconLanguage } from '@tabler/icons-svelte';
	import {
		DropdownMenu,
		DropdownMenuContent,
		DropdownMenuItem,
		DropdownMenuTrigger
	} from './ui/dropdown-menu';
	import { SidebarMenuButton } from './ui/sidebar';
	import { Button } from './ui/button';

	const LANGUAGE_NAMES: Record<Locale, string> = {
		en: 'English',
		de: 'Deutsch',
		es: 'Español',
		fr: 'Français',
		ja: '日本語',
		pt: 'Português',
		zh: '中文'
	};

	let { inSidebar = false }: { inSidebar?: boolean } = $props();

	const locale = getLocale();
</script>

<DropdownMenu>
	<DropdownMenuTrigger>
		{#if inSidebar}
			<SidebarMenuButton tooltipContent={m['language-selector.select-language']()}>
				<IconLanguage class="size-[1.2rem]" />
				<span>{m['language-selector.select-language']()}</span>
			</SidebarMenuButton>
		{:else}
			<Button size="sm" variant="ghost">
				<div class="flex items-center gap-2">
					<IconLanguage class="size-5" />
					<span class="block lg:hidden">{LANGUAGE_NAMES[locale]}</span>
				</div>
			</Button>
		{/if}
	</DropdownMenuTrigger>
	<DropdownMenuContent align="end">
		{#each locales as locale}
			<DropdownMenuItem onclick={() => setLocale(locale)}>
				{LANGUAGE_NAMES[locale]}
			</DropdownMenuItem>
		{/each}
	</DropdownMenuContent>
</DropdownMenu>

// apps/web/src/components/language-selector.tsx
import { Check, Globe } from 'lucide-react'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from './ui/dropdown-menu'
import { Button } from './ui/button'
import { getLocale, locales, setLocale } from '@/paraglide/runtime'
import { setDefaultOptions } from 'date-fns'
import { enUS, de, ptBR, es, fr, ja, zhCN } from 'date-fns/locale'

export function LanguageSelector() {
  const localeMap = {
    en: 'English',
    de: 'Deutsch',
    es: 'Español',
    fr: 'Français',
    ja: '日本語',
    pt: 'Português',
    zh: '中文',
  }
  const dateLocaleMap = {
    en: enUS,
    de: de,
    es: es,
    fr: fr,
    ja: ja,
    pt: ptBR,
    zh: zhCN,
  }
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="icon">
          <Globe className="size-[1.2rem]" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent>
        {locales.map((locale) => (
          <DropdownMenuItem
            onClick={() => {
              setLocale(locale)
              setDefaultOptions({
                locale: dateLocaleMap[locale as keyof typeof dateLocaleMap],
              })
            }}
            key={locale}
          >
            {localeMap[locale as keyof typeof localeMap]}
            {locale === getLocale() ? (
              <Check className="size-[1.2rem]" />
            ) : null}
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
