// app/[locale]/(landing)/_components/footer.tsx
import { Separator } from '@/components/ui/separator'
import { Link } from '@/i18n/navigation'
import NextLink from 'next/link'
import Image from 'next/image'
import { getTranslations } from 'next-intl/server'

export async function Footer() {
  const t = await getTranslations('Landing')
  return (
    <footer id="footer" className="container mx-auto py-24 sm:py-32">
      <div className="p-10 bg-card border border-secondary">
        <div className="gap-6 items-center justify-between max-w-screen-xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          <div className="col-span-full xl:col-span-2">
            <Link href="/" className="flex font-bold items-center">
              <Image src="/vitaes.svg" alt="Vitaes" width={36} height={36} />
              <h3 className="text-2xl">Vitaes</h3>
            </Link>
          </div>
          <Separator className="my-6 col-span-full" />
          <section className="col-span-full">
            <h3 className="">
              {t('footer')}
              <NextLink
                target="_blank"
                href="https://github.com/diegopluna"
                className="text-primary transition-all border-primary hover:border-b-2 ml-1"
              >
                diegopluna
              </NextLink>
            </h3>
          </section>
        </div>
      </div>
    </footer>
  )
}

// src/lib/components/footer.svelte
<script lang="ts">
	import { m } from '$lib/paraglide/messages';
	import { Separator } from './ui/separator';
</script>

<footer id="footer" class="container mx-auto py-24 sm:py-32">
	<div class="rounded-xl border border-secondary bg-card p-10">
		<div
			class="mx-auto grid max-w-screen-xl grid-cols-1 items-center justify-between gap-6 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"
		>
			<div class="col-span-full xl:col-span-2">
				<a href="/" class="flex items-center font-bold">
					<enhanced:img src="$lib/assets/logo.svg" alt="Vitaes" class="size-9" />
					<span class="text-2xl">Vitaes</span>
				</a>
			</div>
			<Separator class="col-span-full my-6" />
			<section class="col-span-full">
				<h3>
					{m['landing.footer']()}
					<a
						href="https://github.com/diegopluna"
						target="_blank"
						rel="noopener noreferrer"
						class="ml-1 border-primary text-primary transition-all hover:border-b-2"
					>
						diegopluna
					</a>
				</h3>
			</section>
		</div>
	</div>
</footer>
